const c=NOOK_CONFIG, notice=(m,bad=false)=>message.innerHTML=`<div class="notice ${bad?'bad':''}">${m}</div>`;
if(!c.supabaseUrl.startsWith('http')){notice('Setup is not complete yet. Follow README.md first.',true);throw new Error('Missing configuration')}
const db=supabase.createClient(c.supabaseUrl,c.supabaseAnonKey);let content=structuredClone(DEFAULT_SITE);
const text=(label,path,val,area=false)=>`<label>${label}${area?`<textarea data-path="${path}">${val||''}</textarea>`:`<input data-path="${path}" value="${val||''}">`}</label>`;
const read=obj=>Object.entries(obj).map(([key,value])=>text(key.replaceAll('_',' '),key,value,typeof value==='string'&&value.length>85)).join('');
function form(){hero.innerHTML=text('Business name','brand',content.brand)+read(Object.fromEntries(Object.entries(content.hero).filter(([k])=>k!=='image')))+`<label>Hero image<input type="file" data-image="hero.image" accept="image/*"></label>`;sections.innerHTML=read(Object.fromEntries(Object.entries(content.intro).map(([k,v])=>['intro.'+k,v])))+text('Collection heading','gallery_title',content.gallery_title)+text('Collection helper text','gallery_text',content.gallery_text,true);items.innerHTML=content.items.map((x,i)=>`<details><summary>${String(i+1).padStart(2,'0')} — ${x.title}</summary><div class="fields">${text('Room',`items.${i}.room`,x.room)}${text('Name',`items.${i}.title`,x.title)}${text('Description',`items.${i}.text`,x.text,true)}<label>Original pattern<select data-path="items.${i}.pattern">${['linen','sheer','velvet','oat','jacquard','roman','stripe','pearl','deepsea'].map(p=>`<option ${x.pattern===p?'selected':''}>${p}</option>`).join('')}</select></label><label>Replace with photo<input type="file" data-image="items.${i}.image" accept="image/*"></label></div>${x.image?`<button type="button" class="remove" data-remove="items.${i}.image">Remove current photo</button>`:''}</details>`).join('');more.innerHTML=`<div class="fields">${text('Process heading','process_title',content.process_title)}</div><h3>Four process steps</h3>${content.steps.map((x,i)=>`<div class="fields step">${text('Step '+(i+1)+' title',`steps.${i}.title`,x.title)}${text('Step '+(i+1)+' description',`steps.${i}.text`,x.text,true)}</div>`).join('')}<h3>Showroom</h3><div class="fields">${Object.entries(content.showroom).map(([k,v])=>text(k.replaceAll('_',' '),'showroom.'+k,v,k==='text')).join('')}</div><h3>Footer</h3><div class="fields">${Object.entries(content.footer).map(([k,v])=>text(k.replaceAll('_',' '),'footer.'+k,v,k==='description')).join('')}</div>`}
function set(path,val){let x=content;const bits=path.split('.');bits.slice(0,-1).forEach(k=>x=x[k]);x[bits.at(-1)]=val}
async function load(){const {data,error}=await db.from('site_content').select('content').eq('id',1).single();if(error){notice('Could not load content. Check the setup steps in README.md.',true);return}content=data.content&&Object.keys(data.content).length?data.content:content;form();editor.hidden=false;login.hidden=true}
signin.onclick=async()=>{const {error}=await db.auth.signInWithPassword({email:email.value,password:password.value});if(error)return notice('Sign-in failed: '+error.message,true);if(email.value.toLowerCase()!==c.adminEmail.toLowerCase())return notice('This email is not the website administrator.',true);load()};
document.addEventListener('input',e=>{if(e.target.dataset.path)set(e.target.dataset.path,e.target.value)});document.addEventListener('click',e=>{if(e.target.dataset.remove){set(e.target.dataset.remove,'');form()}});
document.addEventListener('change',async e=>{const path=e.target.dataset.image,file=e.target.files?.[0];if(!path||!file)return;if(!file.type.startsWith('image/')||file.size>5*1024*1024)return notice('Please use an image under 5 MB.',true);notice('Uploading image…');const ext=file.name.split('.').pop().replace(/[^a-z0-9]/gi,'');const name=`${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await db.storage.from('site-images').upload(name,file,{upsert:false,contentType:file.type});if(error)return notice('Upload failed: '+error.message,true);const {data}=db.storage.from('site-images').getPublicUrl(name);set(path,data.publicUrl);form();notice('Photo is ready. Click Save changes to publish it.');});
editor.onsubmit=async e=>{e.preventDefault();const {error}=await db.from('site_content').update({content,updated_at:new Date().toISOString()}).eq('id',1);if(error)return notice('Save failed: '+error.message,true);notice('Saved — your live website is updated.');};
db.auth.getSession().then(({data})=>{if(data.session)load()});
