window.DEFAULT_SITE={brand:'Nook Studio',
hero:{eyebrow:'Custom Made with Care in Aotearoa',
title:'A window,|dressed in <em>the right light</em>',
text:'Nook Studio is inspired by the sun-soaked warmth of Tuscany & the quiet poetry of Wabi-sabi. One brings light, the other embraces shadow-together craft your nook, filled with gentle light, natural texture, and unhurried ease, shaped through thoughtful craftsmanship, timeless fabrics, and tailored design. ',
primary_label:'Book a Measure & Fit',
primary_link:'mailto:nookstudionz@gmail.com',
secondary_label:'Browse the Collection',
secondary_link:'#gallery',
image:''},
intro:{title:"We're not selling curtains — we're setting the mood of a room",
text:"Blackout, acoustic softening, sheer daylight, hard-wearing everyday fabric — we've turned the directions people ask for most into a set you can actually see and feel before you commit."},
gallery_title:'Nine Ways to Shape the Light',
gallery_text:"Hover over a swatch — it draws open like a real curtain to show how it's used.",
items:[['Fabric Curtains','Natural Linen Blackout','Heavy linen weave with strong blackout, ideal for west-facing rooms that run hot in summer.','linen'],
       ['Sheer Curtains','Misty Blue Sheer','Light-diffusing voile that softens daytime glare, usually layered under a blackout panel.','sheer'],
       ['Roller Shades','Midnight Velvet','Dense, weighted drape that dampens sound and cold — good for south-facing bedrooms in winter.','velvet'],
       ['Roman Shades','Oatmeal Cotton-Linen','Warm-toned cotton-linen blend that resists fading and wipes clean easily.','oat'],
       ['Venetian Blinds','Cloud Jacquard','Geometric jacquard weave with a subtle sheen shift, suited to a quiet home office.','jacquard'],
       ['Zebra Shades','Sky Blue Roman Shade','Horizontal pleats that stack neatly out of the way — great for a small window above the sink.','roman'],
       ["Honeycomb Shades' Room",'Grey-Blue Stripe',"Durable striped weave, playful but grounded — built for kids' rooms and play areas.",'stripe'],
       ['Shangri-La Shades','Pearl White Blackout','Light-toned blackout fabric that bounces soft light around — good for making a small room feel bigger.','pearl'],
       ['Vertical Shades','Deep Sea Velvet','Rich, saturated velvet with full blackout — for a main bedroom built around sleeping early.','deepsea'],
       ['Sheer Vertical Shades','Deep Sea Velvet','Rich, saturated velvet with full blackout — for a main bedroom built around sleeping early.','deepsea']].
map(([curtain,title,text,pattern])=>({curtain,title,text,pattern,image:''})),
process_title:'From first measure to hung and finished, in four steps',
steps:[['Choose in Store','Feel real samples and see how they actually drape at our Rolleston showroom before you choose colour and weight.'],['In-Home Measure','Our technician measures your windows on-site and confirms the mounting style and track type.'],['Cut & Sewn to Fit','Every panel is cut and sewn for your exact window, with pleat ratio and drop length dialled in.'],['Fit & Final Check','We install on-site and adjust in place, checking smooth operation and a clean blackout seal.']].map(([title,text])=>({title,text})),
showroom:{title:'Feel the fabric before you decide',
text:'Photos and screens never show colour quite right. Come by our Rolleston showroom to feel the weight, drape and true colour of any fabric in person.',
address:'108 Shillingford Blvd, Rolleston, New Zealand',
email:'nookstudionz@gmail.com',
phone:'028-8523-8835',
visiting:'Please Book an Appointment Before Visiting the Showroom'},
footer:{description:'A Rolleston-based custom curtain studio, handling fabric selection, measuring and installation from start to finish.',
copyright:'© 2026 Nook Studio. All rights reserved.',
tagline:'Custom Made with Care in New Zealand.'}};
