window.DEFAULT_SITE={brand:'Nook Studio',
hero:{eyebrow:'Custom Made Curtains & Shades with Heart',
title:'A window,|dressed in <em>the right light</em>',
text:'Nook Studio crafts your nook with gentle light, natural texture, and unhurried ease, shaped through thoughtful craftsmanship, timeless fabrics, and tailored design.',
primary_label:'Book a Free Consultation',
primary_link:'mailto:nookstudionz@gmail.com',
secondary_label:'Browse the Collection',
secondary_link:'#gallery',
image:''},
intro:{title:"We're not selling curtains — we're setting the mood of a room",
text:"Nook Studio is inspired by the sun-soaked warmth of Tuscany & the quiet poetry of Wabi-sabi. One brings light, the other embraces shadow."},
gallery_title:'Nine Ways to Shape the Light',
gallery_text:"Hover over a swatch — it draws open like a real curtain to show how it's used.",
items:[['Fabric Curtains','Fabric Curtains','Heavy linen weave with strong blackout, ideal for west-facing rooms that run hot in summer.','linen'],
       ['Sheer Curtains','Sheer Curtains','Light-diffusing voile that softens daytime glare, usually layered under a blackout panel.','sheer'],
       ['Roller Shades','Roller Shades','Dense, weighted drape that dampens sound and cold — good for south-facing bedrooms in winter.','velvet'],
       ['Roman Shades','Roman Shades','Warm-toned cotton-linen blend that resists fading and wipes clean easily.','oat'],
       ['Venetian Blinds','Venetian Blinds','Geometric jacquard weave with a subtle sheen shift, suited to a quiet home office.','jacquard'],
       ['Zebra Shades','Zebra Shades','Horizontal pleats that stack neatly out of the way — great for a small window above the sink.','roman'],
       ['Honeycomb Shades','Honeycomb Shades',"Durable striped weave, playful but grounded — built for kids' rooms and play areas.",'stripe'],
       ['Shangri-La Shades','Shangri-La Shades','Light-toned blackout fabric that bounces soft light around — good for making a small room feel bigger.','pearl'],
       ['Vertical Shades','Vertical Shades','Rich, saturated velvet with full blackout — for a main bedroom built around sleeping early.','deepsea']].
map(([curtain,title,text,pattern])=>({curtain,title,text,pattern,image:''})),
process_title:'From initial consultation to fit and finish in four steps',
steps:[['Free Consultation ','Our team offers thoughtful, tailored advice for your home based on your style, needs, and preferences.'],['Free In-Home Measure','Our technician measures your windows on-site for free and confirms the mounting style and track type.'],['Selection At Our Studio','Feel real samples and see how they actually drape at our studio before you choose fabrics, colors, and finishes.'],['Installation & Final Check','We fit and install on-site and adjust in place, checking smooth operation and a clean blackout seal.']].map(([title,text])=>({title,text})),
showroom:{title:'Experience Collections' Texture, Drape, Colors',
text:'Book a studio visit to feel our fabrics' rich texture, natural drape, and authentic color.',
address:'108 Shillingford Blvd, Rolleston, New Zealand',
email:'nookstudionz@gmail.com',
phone:'028-8523-8835',
visiting:'Please book before visiting the studio.'},
footer:{description:'Nook Studio offers a complete, end-to-end service tailored to your home and lifestyle. We guide you through our curated fabric selection, take care of precision measuring, and complete the journey with flawless professional installation.',
copyright:'© 2026 Nook Studio. All rights reserved.',
tagline:'Custom Made Curtains & Blinds with Care'}};
